### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Fridgey** [Synapz1/Paintball#27]
Why would getTeamWithLeastPlayers ever return null? It's breaking team balancing.

**Comment by Synapz1** [comment]
I saw. I am going to assume this is why..

http://prntscr.com/bsu1k7

It only happens on FFA. I think it has something to do with the fact that FFA does not need team balancing, since everyone is on their own team. So I will turn off Team Balancing for FFA and just in case put in a null check to make sure getTeamWithLessPlayers is never null.

**Comment by Synapz1** [comment]
I just temp removed it and added the permission so we have time to go through it I guess.

It works fine for CTF but not for FFA. So I also overrode it for FFA to not do anything and I added a null check. And commented it out just in case
